// <auto-generated/>

namespace ArtistAssistant
{
    partial class ArtistAssistantForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ArtistAssistantForm));
            this.toolbarPanel = new System.Windows.Forms.Panel();
            this.uploadButton = new System.Windows.Forms.Button();
            this.newObjectButton = new System.Windows.Forms.Button();
            this.selectButton = new System.Windows.Forms.Button();
            this.bringToFrontButton = new System.Windows.Forms.Button();
            this.sendToBackButton = new System.Windows.Forms.Button();
            this.undoButton = new System.Windows.Forms.Button();
            this.duplicateButton = new System.Windows.Forms.Button();
            this.deleteButton = new System.Windows.Forms.Button();
            this.scaleButton = new System.Windows.Forms.Button();
            this.moveButton = new System.Windows.Forms.Button();
            this.downloadButton = new System.Windows.Forms.Button();
            this.newDrawingButton = new System.Windows.Forms.Button();
            this.createDrawingMenuPanel = new System.Windows.Forms.Panel();
            this.startDrawingButton = new System.Windows.Forms.Button();
            this.backgroundFileButton = new System.Windows.Forms.Button();
            this.colorButton = new System.Windows.Forms.Button();
            this.backgroundColorDialog = new System.Windows.Forms.ColorDialog();
            this.openFileDialog = new System.Windows.Forms.OpenFileDialog();
            this.addItemMenuPanel = new System.Windows.Forms.Panel();
            this.addItemHeightLabel = new System.Windows.Forms.Label();
            this.addItemWidthLabel = new System.Windows.Forms.Label();
            this.addHeightNumericUpDown = new System.Windows.Forms.NumericUpDown();
            this.addWidthNumericUpDown = new System.Windows.Forms.NumericUpDown();
            this.treePictureBox = new System.Windows.Forms.PictureBox();
            this.rainPictureBox = new System.Windows.Forms.PictureBox();
            this.pondPictureBox = new System.Windows.Forms.PictureBox();
            this.pinePictureBox = new System.Windows.Forms.PictureBox();
            this.mountainPictureBox = new System.Windows.Forms.PictureBox();
            this.cloudPictureBox = new System.Windows.Forms.PictureBox();
            this.drawingPictureBox = new System.Windows.Forms.PictureBox();
            this.scaleItemMenuPanel = new System.Windows.Forms.Panel();
            this.scaleObjectButton = new System.Windows.Forms.Button();
            this.scaleHeightLabel = new System.Windows.Forms.Label();
            this.scaleWidthLabel = new System.Windows.Forms.Label();
            this.scaleHeightNumericUpDown = new System.Windows.Forms.NumericUpDown();
            this.scaleWidthNumericUpDown = new System.Windows.Forms.NumericUpDown();
            this.toolTip = new System.Windows.Forms.ToolTip(this.components);
            this.fileUploadMenuPanel = new System.Windows.Forms.Panel();
            this.uploadToCloudButton = new System.Windows.Forms.Button();
            this.uploadFileNameTextBox = new System.Windows.Forms.TextBox();
            this.uploadFileNameLabel = new System.Windows.Forms.Label();
            this.downloadFileMenuPanel = new System.Windows.Forms.Panel();
            this.downloadFromCloudButton = new System.Windows.Forms.Button();
            this.uploadedFileListBox = new System.Windows.Forms.ListBox();
            this.toolbarPanel.SuspendLayout();
            this.createDrawingMenuPanel.SuspendLayout();
            this.addItemMenuPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.addHeightNumericUpDown)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.addWidthNumericUpDown)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.treePictureBox)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.rainPictureBox)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pondPictureBox)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pinePictureBox)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.mountainPictureBox)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cloudPictureBox)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.drawingPictureBox)).BeginInit();
            this.scaleItemMenuPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.scaleHeightNumericUpDown)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.scaleWidthNumericUpDown)).BeginInit();
            this.fileUploadMenuPanel.SuspendLayout();
            this.downloadFileMenuPanel.SuspendLayout();
            this.SuspendLayout();
            // 
            // toolbarPanel
            // 
            this.toolbarPanel.BackColor = System.Drawing.SystemColors.ControlDark;
            this.toolbarPanel.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.toolbarPanel.Controls.Add(this.uploadButton);
            this.toolbarPanel.Controls.Add(this.newObjectButton);
            this.toolbarPanel.Controls.Add(this.selectButton);
            this.toolbarPanel.Controls.Add(this.bringToFrontButton);
            this.toolbarPanel.Controls.Add(this.sendToBackButton);
            this.toolbarPanel.Controls.Add(this.undoButton);
            this.toolbarPanel.Controls.Add(this.duplicateButton);
            this.toolbarPanel.Controls.Add(this.deleteButton);
            this.toolbarPanel.Controls.Add(this.scaleButton);
            this.toolbarPanel.Controls.Add(this.moveButton);
            this.toolbarPanel.Controls.Add(this.downloadButton);
            this.toolbarPanel.Controls.Add(this.newDrawingButton);
            this.toolbarPanel.Location = new System.Drawing.Point(4, 5);
            this.toolbarPanel.Margin = new System.Windows.Forms.Padding(1, 1, 1, 1);
            this.toolbarPanel.Name = "toolbarPanel";
            this.toolbarPanel.Size = new System.Drawing.Size(60, 674);
            this.toolbarPanel.TabIndex = 0;
            // 
            // uploadButton
            // 
            this.uploadButton.BackColor = System.Drawing.Color.White;
            this.uploadButton.BackgroundImage = global::ArtistAssistant.Properties.Resources.upload;
            this.uploadButton.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.uploadButton.Location = new System.Drawing.Point(3, 115);
            this.uploadButton.Name = "uploadButton";
            this.uploadButton.Size = new System.Drawing.Size(50, 50);
            this.uploadButton.TabIndex = 2;
            this.uploadButton.UseVisualStyleBackColor = false;
            this.uploadButton.Click += new System.EventHandler(this.UploadButton_Click);
            this.uploadButton.KeyDown += new System.Windows.Forms.KeyEventHandler(this.ArtistAssistantForm_KeyDown);
            // 
            // newObjectButton
            // 
            this.newObjectButton.BackColor = System.Drawing.Color.White;
            this.newObjectButton.BackgroundImage = global::ArtistAssistant.Properties.Resources.additem1;
            this.newObjectButton.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.newObjectButton.Location = new System.Drawing.Point(3, 283);
            this.newObjectButton.Name = "newObjectButton";
            this.newObjectButton.Size = new System.Drawing.Size(50, 50);
            this.newObjectButton.TabIndex = 5;
            this.newObjectButton.UseVisualStyleBackColor = false;
            this.newObjectButton.Click += new System.EventHandler(this.NewObjectButton_Click);
            this.newObjectButton.KeyDown += new System.Windows.Forms.KeyEventHandler(this.ArtistAssistantForm_KeyDown);
            // 
            // selectButton
            // 
            this.selectButton.BackColor = System.Drawing.Color.White;
            this.selectButton.BackgroundImage = global::ArtistAssistant.Properties.Resources.cursor;
            this.selectButton.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.selectButton.Location = new System.Drawing.Point(3, 171);
            this.selectButton.Name = "selectButton";
            this.selectButton.Size = new System.Drawing.Size(50, 50);
            this.selectButton.TabIndex = 3;
            this.selectButton.UseVisualStyleBackColor = false;
            this.selectButton.Click += new System.EventHandler(this.SelectButton_Click);
            this.selectButton.KeyDown += new System.Windows.Forms.KeyEventHandler(this.ArtistAssistantForm_KeyDown);
            // 
            // bringToFrontButton
            // 
            this.bringToFrontButton.BackColor = System.Drawing.Color.White;
            this.bringToFrontButton.BackgroundImage = global::ArtistAssistant.Properties.Resources.bringtofront;
            this.bringToFrontButton.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bringToFrontButton.Location = new System.Drawing.Point(3, 451);
            this.bringToFrontButton.Name = "bringToFrontButton";
            this.bringToFrontButton.Size = new System.Drawing.Size(50, 50);
            this.bringToFrontButton.TabIndex = 8;
            this.bringToFrontButton.UseVisualStyleBackColor = false;
            this.bringToFrontButton.Click += new System.EventHandler(this.BringToFrontButton_Click);
            this.bringToFrontButton.KeyDown += new System.Windows.Forms.KeyEventHandler(this.ArtistAssistantForm_KeyDown);
            // 
            // sendToBackButton
            // 
            this.sendToBackButton.BackColor = System.Drawing.Color.White;
            this.sendToBackButton.BackgroundImage = global::ArtistAssistant.Properties.Resources.sendtoback;
            this.sendToBackButton.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.sendToBackButton.Location = new System.Drawing.Point(3, 507);
            this.sendToBackButton.Name = "sendToBackButton";
            this.sendToBackButton.Size = new System.Drawing.Size(50, 50);
            this.sendToBackButton.TabIndex = 9;
            this.sendToBackButton.UseVisualStyleBackColor = false;
            this.sendToBackButton.Click += new System.EventHandler(this.SendToBackButton_Click);
            this.sendToBackButton.KeyDown += new System.Windows.Forms.KeyEventHandler(this.ArtistAssistantForm_KeyDown);
            // 
            // undoButton
            // 
            this.undoButton.BackColor = System.Drawing.Color.White;
            this.undoButton.BackgroundImage = global::ArtistAssistant.Properties.Resources.undo;
            this.undoButton.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.undoButton.Location = new System.Drawing.Point(3, 619);
            this.undoButton.Name = "undoButton";
            this.undoButton.Size = new System.Drawing.Size(50, 50);
            this.undoButton.TabIndex = 11;
            this.undoButton.UseVisualStyleBackColor = false;
            this.undoButton.Click += new System.EventHandler(this.UndoButton_Click);
            this.undoButton.KeyDown += new System.Windows.Forms.KeyEventHandler(this.ArtistAssistantForm_KeyDown);
            // 
            // duplicateButton
            // 
            this.duplicateButton.BackColor = System.Drawing.Color.White;
            this.duplicateButton.BackgroundImage = global::ArtistAssistant.Properties.Resources.duplicate;
            this.duplicateButton.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.duplicateButton.Location = new System.Drawing.Point(3, 395);
            this.duplicateButton.Name = "duplicateButton";
            this.duplicateButton.Size = new System.Drawing.Size(50, 50);
            this.duplicateButton.TabIndex = 7;
            this.duplicateButton.UseVisualStyleBackColor = false;
            this.duplicateButton.Click += new System.EventHandler(this.DuplicateButton_Click);
            this.duplicateButton.KeyDown += new System.Windows.Forms.KeyEventHandler(this.ArtistAssistantForm_KeyDown);
            // 
            // deleteButton
            // 
            this.deleteButton.BackColor = System.Drawing.Color.White;
            this.deleteButton.BackgroundImage = global::ArtistAssistant.Properties.Resources.delete;
            this.deleteButton.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.deleteButton.Location = new System.Drawing.Point(3, 563);
            this.deleteButton.Name = "deleteButton";
            this.deleteButton.Size = new System.Drawing.Size(50, 50);
            this.deleteButton.TabIndex = 10;
            this.deleteButton.UseVisualStyleBackColor = false;
            this.deleteButton.Click += new System.EventHandler(this.DeleteButton_Click);
            this.deleteButton.KeyDown += new System.Windows.Forms.KeyEventHandler(this.ArtistAssistantForm_KeyDown);
            // 
            // scaleButton
            // 
            this.scaleButton.BackColor = System.Drawing.Color.White;
            this.scaleButton.BackgroundImage = global::ArtistAssistant.Properties.Resources.resize;
            this.scaleButton.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.scaleButton.Location = new System.Drawing.Point(3, 339);
            this.scaleButton.Name = "scaleButton";
            this.scaleButton.Size = new System.Drawing.Size(50, 50);
            this.scaleButton.TabIndex = 6;
            this.scaleButton.UseVisualStyleBackColor = false;
            this.scaleButton.Click += new System.EventHandler(this.ScaleButton_Click);
            this.scaleButton.KeyDown += new System.Windows.Forms.KeyEventHandler(this.ArtistAssistantForm_KeyDown);
            // 
            // moveButton
            // 
            this.moveButton.BackColor = System.Drawing.Color.White;
            this.moveButton.BackgroundImage = global::ArtistAssistant.Properties.Resources.move;
            this.moveButton.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.moveButton.Location = new System.Drawing.Point(3, 227);
            this.moveButton.Name = "moveButton";
            this.moveButton.Size = new System.Drawing.Size(50, 50);
            this.moveButton.TabIndex = 4;
            this.moveButton.UseVisualStyleBackColor = false;
            this.moveButton.Click += new System.EventHandler(this.MoveButton_Click);
            this.moveButton.KeyDown += new System.Windows.Forms.KeyEventHandler(this.ArtistAssistantForm_KeyDown);
            // 
            // downloadButton
            // 
            this.downloadButton.BackColor = System.Drawing.Color.White;
            this.downloadButton.BackgroundImage = global::ArtistAssistant.Properties.Resources.download;
            this.downloadButton.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.downloadButton.Location = new System.Drawing.Point(3, 59);
            this.downloadButton.Name = "downloadButton";
            this.downloadButton.Size = new System.Drawing.Size(50, 50);
            this.downloadButton.TabIndex = 1;
            this.downloadButton.UseVisualStyleBackColor = false;
            this.downloadButton.Click += new System.EventHandler(this.DownloadButton_Click);
            this.downloadButton.KeyDown += new System.Windows.Forms.KeyEventHandler(this.ArtistAssistantForm_KeyDown);
            // 
            // newDrawingButton
            // 
            this.newDrawingButton.BackColor = System.Drawing.Color.White;
            this.newDrawingButton.BackgroundImage = global::ArtistAssistant.Properties.Resources.newdrawing;
            this.newDrawingButton.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.newDrawingButton.Location = new System.Drawing.Point(3, 3);
            this.newDrawingButton.Name = "newDrawingButton";
            this.newDrawingButton.Size = new System.Drawing.Size(50, 50);
            this.newDrawingButton.TabIndex = 0;
            this.newDrawingButton.UseVisualStyleBackColor = false;
            this.newDrawingButton.Click += new System.EventHandler(this.NewDrawingButton_Click);
            this.newDrawingButton.KeyDown += new System.Windows.Forms.KeyEventHandler(this.ArtistAssistantForm_KeyDown);
            // 
            // createDrawingMenuPanel
            // 
            this.createDrawingMenuPanel.BackColor = System.Drawing.SystemColors.ControlDark;
            this.createDrawingMenuPanel.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.createDrawingMenuPanel.Controls.Add(this.startDrawingButton);
            this.createDrawingMenuPanel.Controls.Add(this.backgroundFileButton);
            this.createDrawingMenuPanel.Controls.Add(this.colorButton);
            this.createDrawingMenuPanel.Location = new System.Drawing.Point(65, 5);
            this.createDrawingMenuPanel.Name = "createDrawingMenuPanel";
            this.createDrawingMenuPanel.Size = new System.Drawing.Size(139, 100);
            this.createDrawingMenuPanel.TabIndex = 0;
            // 
            // startDrawingButton
            // 
            this.startDrawingButton.BackColor = System.Drawing.Color.White;
            this.startDrawingButton.Location = new System.Drawing.Point(17, 64);
            this.startDrawingButton.Name = "startDrawingButton";
            this.startDrawingButton.Size = new System.Drawing.Size(99, 23);
            this.startDrawingButton.TabIndex = 2;
            this.startDrawingButton.TabStop = false;
            this.startDrawingButton.Text = "Start Drawing";
            this.startDrawingButton.UseVisualStyleBackColor = false;
            this.startDrawingButton.Click += new System.EventHandler(this.StartDrawingButton_Click);
            this.startDrawingButton.KeyDown += new System.Windows.Forms.KeyEventHandler(this.ArtistAssistantForm_KeyDown);
            // 
            // backgroundFileButton
            // 
            this.backgroundFileButton.BackColor = System.Drawing.Color.White;
            this.backgroundFileButton.Location = new System.Drawing.Point(17, 35);
            this.backgroundFileButton.Name = "backgroundFileButton";
            this.backgroundFileButton.Size = new System.Drawing.Size(99, 23);
            this.backgroundFileButton.TabIndex = 1;
            this.backgroundFileButton.TabStop = false;
            this.backgroundFileButton.Text = "Select File";
            this.backgroundFileButton.UseVisualStyleBackColor = false;
            this.backgroundFileButton.Click += new System.EventHandler(this.BackgroundFileButton_Click);
            this.backgroundFileButton.KeyDown += new System.Windows.Forms.KeyEventHandler(this.ArtistAssistantForm_KeyDown);
            // 
            // colorButton
            // 
            this.colorButton.BackColor = System.Drawing.Color.White;
            this.colorButton.Location = new System.Drawing.Point(17, 6);
            this.colorButton.Name = "colorButton";
            this.colorButton.Size = new System.Drawing.Size(99, 23);
            this.colorButton.TabIndex = 0;
            this.colorButton.TabStop = false;
            this.colorButton.Text = "Select Color";
            this.colorButton.UseVisualStyleBackColor = false;
            this.colorButton.Click += new System.EventHandler(this.ColorButton_Click);
            this.colorButton.KeyDown += new System.Windows.Forms.KeyEventHandler(this.ArtistAssistantForm_KeyDown);
            // 
            // addItemMenuPanel
            // 
            this.addItemMenuPanel.BackColor = System.Drawing.SystemColors.ControlDark;
            this.addItemMenuPanel.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.addItemMenuPanel.Controls.Add(this.addItemHeightLabel);
            this.addItemMenuPanel.Controls.Add(this.addItemWidthLabel);
            this.addItemMenuPanel.Controls.Add(this.addHeightNumericUpDown);
            this.addItemMenuPanel.Controls.Add(this.addWidthNumericUpDown);
            this.addItemMenuPanel.Controls.Add(this.treePictureBox);
            this.addItemMenuPanel.Controls.Add(this.rainPictureBox);
            this.addItemMenuPanel.Controls.Add(this.pondPictureBox);
            this.addItemMenuPanel.Controls.Add(this.pinePictureBox);
            this.addItemMenuPanel.Controls.Add(this.mountainPictureBox);
            this.addItemMenuPanel.Controls.Add(this.cloudPictureBox);
            this.addItemMenuPanel.Location = new System.Drawing.Point(65, 289);
            this.addItemMenuPanel.Name = "addItemMenuPanel";
            this.addItemMenuPanel.Size = new System.Drawing.Size(139, 141);
            this.addItemMenuPanel.TabIndex = 3;
            // 
            // addItemHeightLabel
            // 
            this.addItemHeightLabel.AutoSize = true;
            this.addItemHeightLabel.Location = new System.Drawing.Point(23, 113);
            this.addItemHeightLabel.Name = "addItemHeightLabel";
            this.addItemHeightLabel.Size = new System.Drawing.Size(41, 13);
            this.addItemHeightLabel.TabIndex = 10;
            this.addItemHeightLabel.Text = "Height:";
            // 
            // addItemWidthLabel
            // 
            this.addItemWidthLabel.AutoSize = true;
            this.addItemWidthLabel.Location = new System.Drawing.Point(26, 87);
            this.addItemWidthLabel.Name = "addItemWidthLabel";
            this.addItemWidthLabel.Size = new System.Drawing.Size(38, 13);
            this.addItemWidthLabel.TabIndex = 9;
            this.addItemWidthLabel.Text = "Width:";
            // 
            // addHeightNumericUpDown
            // 
            this.addHeightNumericUpDown.Location = new System.Drawing.Point(70, 111);
            this.addHeightNumericUpDown.Maximum = new decimal(new int[] {
            3000,
            0,
            0,
            0});
            this.addHeightNumericUpDown.Name = "addHeightNumericUpDown";
            this.addHeightNumericUpDown.Size = new System.Drawing.Size(57, 20);
            this.addHeightNumericUpDown.TabIndex = 8;
            this.addHeightNumericUpDown.TabStop = false;
            this.addHeightNumericUpDown.Value = new decimal(new int[] {
            40,
            0,
            0,
            0});
            this.addHeightNumericUpDown.KeyDown += new System.Windows.Forms.KeyEventHandler(this.ArtistAssistantForm_KeyDown);
            // 
            // addWidthNumericUpDown
            // 
            this.addWidthNumericUpDown.Location = new System.Drawing.Point(70, 85);
            this.addWidthNumericUpDown.Maximum = new decimal(new int[] {
            3000,
            0,
            0,
            0});
            this.addWidthNumericUpDown.Name = "addWidthNumericUpDown";
            this.addWidthNumericUpDown.Size = new System.Drawing.Size(57, 20);
            this.addWidthNumericUpDown.TabIndex = 7;
            this.addWidthNumericUpDown.TabStop = false;
            this.addWidthNumericUpDown.Value = new decimal(new int[] {
            40,
            0,
            0,
            0});
            this.addWidthNumericUpDown.KeyDown += new System.Windows.Forms.KeyEventHandler(this.ArtistAssistantForm_KeyDown);
            // 
            // treePictureBox
            // 
            this.treePictureBox.BackColor = System.Drawing.Color.White;
            this.treePictureBox.BackgroundImage = global::ArtistAssistant.Properties.Resources.Tree;
            this.treePictureBox.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.treePictureBox.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.treePictureBox.Location = new System.Drawing.Point(91, 44);
            this.treePictureBox.Name = "treePictureBox";
            this.treePictureBox.Size = new System.Drawing.Size(35, 35);
            this.treePictureBox.TabIndex = 5;
            this.treePictureBox.TabStop = false;
            this.treePictureBox.Click += new System.EventHandler(this.TreePictureBox_Click);
            // 
            // rainPictureBox
            // 
            this.rainPictureBox.BackColor = System.Drawing.Color.White;
            this.rainPictureBox.BackgroundImage = global::ArtistAssistant.Properties.Resources.Rain;
            this.rainPictureBox.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.rainPictureBox.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.rainPictureBox.Location = new System.Drawing.Point(50, 44);
            this.rainPictureBox.Name = "rainPictureBox";
            this.rainPictureBox.Size = new System.Drawing.Size(35, 35);
            this.rainPictureBox.TabIndex = 4;
            this.rainPictureBox.TabStop = false;
            this.rainPictureBox.Click += new System.EventHandler(this.RainPictureBox_Click);
            // 
            // pondPictureBox
            // 
            this.pondPictureBox.BackColor = System.Drawing.Color.White;
            this.pondPictureBox.BackgroundImage = global::ArtistAssistant.Properties.Resources.Pond;
            this.pondPictureBox.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.pondPictureBox.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.pondPictureBox.Location = new System.Drawing.Point(9, 44);
            this.pondPictureBox.Name = "pondPictureBox";
            this.pondPictureBox.Size = new System.Drawing.Size(35, 35);
            this.pondPictureBox.TabIndex = 3;
            this.pondPictureBox.TabStop = false;
            this.pondPictureBox.Click += new System.EventHandler(this.PondPictureBox_Click);
            // 
            // pinePictureBox
            // 
            this.pinePictureBox.BackColor = System.Drawing.Color.White;
            this.pinePictureBox.BackgroundImage = global::ArtistAssistant.Properties.Resources.Pine;
            this.pinePictureBox.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.pinePictureBox.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.pinePictureBox.Location = new System.Drawing.Point(91, 3);
            this.pinePictureBox.Name = "pinePictureBox";
            this.pinePictureBox.Size = new System.Drawing.Size(35, 35);
            this.pinePictureBox.TabIndex = 2;
            this.pinePictureBox.TabStop = false;
            this.pinePictureBox.Click += new System.EventHandler(this.PinePictureBox_Click);
            // 
            // mountainPictureBox
            // 
            this.mountainPictureBox.BackColor = System.Drawing.Color.White;
            this.mountainPictureBox.BackgroundImage = global::ArtistAssistant.Properties.Resources.Mountain;
            this.mountainPictureBox.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.mountainPictureBox.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.mountainPictureBox.Location = new System.Drawing.Point(50, 3);
            this.mountainPictureBox.Name = "mountainPictureBox";
            this.mountainPictureBox.Size = new System.Drawing.Size(35, 35);
            this.mountainPictureBox.TabIndex = 1;
            this.mountainPictureBox.TabStop = false;
            this.mountainPictureBox.Click += new System.EventHandler(this.MountainPictureBox_Click);
            // 
            // cloudPictureBox
            // 
            this.cloudPictureBox.BackColor = System.Drawing.Color.White;
            this.cloudPictureBox.BackgroundImage = global::ArtistAssistant.Properties.Resources.Cloud;
            this.cloudPictureBox.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.cloudPictureBox.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.cloudPictureBox.Location = new System.Drawing.Point(9, 3);
            this.cloudPictureBox.Name = "cloudPictureBox";
            this.cloudPictureBox.Size = new System.Drawing.Size(35, 35);
            this.cloudPictureBox.TabIndex = 0;
            this.cloudPictureBox.TabStop = false;
            this.cloudPictureBox.Click += new System.EventHandler(this.CloudPictureBox_Click);
            // 
            // drawingPictureBox
            // 
            this.drawingPictureBox.Location = new System.Drawing.Point(68, 5);
            this.drawingPictureBox.Name = "drawingPictureBox";
            this.drawingPictureBox.Size = new System.Drawing.Size(1317, 674);
            this.drawingPictureBox.TabIndex = 12;
            this.drawingPictureBox.TabStop = false;
            this.drawingPictureBox.MouseClick += new System.Windows.Forms.MouseEventHandler(this.DrawingPictureBox_MouseClick);
            // 
            // scaleItemMenuPanel
            // 
            this.scaleItemMenuPanel.BackColor = System.Drawing.SystemColors.ControlDark;
            this.scaleItemMenuPanel.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.scaleItemMenuPanel.Controls.Add(this.scaleObjectButton);
            this.scaleItemMenuPanel.Controls.Add(this.scaleHeightLabel);
            this.scaleItemMenuPanel.Controls.Add(this.scaleWidthLabel);
            this.scaleItemMenuPanel.Controls.Add(this.scaleHeightNumericUpDown);
            this.scaleItemMenuPanel.Controls.Add(this.scaleWidthNumericUpDown);
            this.scaleItemMenuPanel.Location = new System.Drawing.Point(65, 346);
            this.scaleItemMenuPanel.Name = "scaleItemMenuPanel";
            this.scaleItemMenuPanel.Size = new System.Drawing.Size(139, 105);
            this.scaleItemMenuPanel.TabIndex = 11;
            // 
            // scaleObjectButton
            // 
            this.scaleObjectButton.BackColor = System.Drawing.Color.White;
            this.scaleObjectButton.Location = new System.Drawing.Point(21, 60);
            this.scaleObjectButton.Name = "scaleObjectButton";
            this.scaleObjectButton.Size = new System.Drawing.Size(99, 23);
            this.scaleObjectButton.TabIndex = 3;
            this.scaleObjectButton.TabStop = false;
            this.scaleObjectButton.Text = "Scale";
            this.scaleObjectButton.UseVisualStyleBackColor = false;
            this.scaleObjectButton.Click += new System.EventHandler(this.ScaleObjectButton_Click);
            this.scaleObjectButton.KeyDown += new System.Windows.Forms.KeyEventHandler(this.ArtistAssistantForm_KeyDown);
            // 
            // scaleHeightLabel
            // 
            this.scaleHeightLabel.AutoSize = true;
            this.scaleHeightLabel.Location = new System.Drawing.Point(16, 36);
            this.scaleHeightLabel.Name = "scaleHeightLabel";
            this.scaleHeightLabel.Size = new System.Drawing.Size(41, 13);
            this.scaleHeightLabel.TabIndex = 10;
            this.scaleHeightLabel.Text = "Height:";
            // 
            // scaleWidthLabel
            // 
            this.scaleWidthLabel.AutoSize = true;
            this.scaleWidthLabel.Location = new System.Drawing.Point(19, 10);
            this.scaleWidthLabel.Name = "scaleWidthLabel";
            this.scaleWidthLabel.Size = new System.Drawing.Size(38, 13);
            this.scaleWidthLabel.TabIndex = 9;
            this.scaleWidthLabel.Text = "Width:";
            // 
            // scaleHeightNumericUpDown
            // 
            this.scaleHeightNumericUpDown.Location = new System.Drawing.Point(63, 34);
            this.scaleHeightNumericUpDown.Maximum = new decimal(new int[] {
            3000,
            0,
            0,
            0});
            this.scaleHeightNumericUpDown.Name = "scaleHeightNumericUpDown";
            this.scaleHeightNumericUpDown.Size = new System.Drawing.Size(57, 20);
            this.scaleHeightNumericUpDown.TabIndex = 8;
            this.scaleHeightNumericUpDown.TabStop = false;
            this.scaleHeightNumericUpDown.Value = new decimal(new int[] {
            40,
            0,
            0,
            0});
            this.scaleHeightNumericUpDown.KeyDown += new System.Windows.Forms.KeyEventHandler(this.ArtistAssistantForm_KeyDown);
            // 
            // scaleWidthNumericUpDown
            // 
            this.scaleWidthNumericUpDown.Location = new System.Drawing.Point(63, 8);
            this.scaleWidthNumericUpDown.Maximum = new decimal(new int[] {
            3000,
            0,
            0,
            0});
            this.scaleWidthNumericUpDown.Name = "scaleWidthNumericUpDown";
            this.scaleWidthNumericUpDown.Size = new System.Drawing.Size(57, 20);
            this.scaleWidthNumericUpDown.TabIndex = 7;
            this.scaleWidthNumericUpDown.TabStop = false;
            this.scaleWidthNumericUpDown.Value = new decimal(new int[] {
            40,
            0,
            0,
            0});
            this.scaleWidthNumericUpDown.KeyDown += new System.Windows.Forms.KeyEventHandler(this.ArtistAssistantForm_KeyDown);
            // 
            // fileUploadMenuPanel
            // 
            this.fileUploadMenuPanel.BackColor = System.Drawing.SystemColors.ControlDark;
            this.fileUploadMenuPanel.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.fileUploadMenuPanel.Controls.Add(this.uploadFileNameLabel);
            this.fileUploadMenuPanel.Controls.Add(this.uploadToCloudButton);
            this.fileUploadMenuPanel.Controls.Add(this.uploadFileNameTextBox);
            this.fileUploadMenuPanel.Location = new System.Drawing.Point(65, 121);
            this.fileUploadMenuPanel.Name = "fileUploadMenuPanel";
            this.fileUploadMenuPanel.Size = new System.Drawing.Size(139, 86);
            this.fileUploadMenuPanel.TabIndex = 3;
            // 
            // uploadToCloudButton
            // 
            this.uploadToCloudButton.BackColor = System.Drawing.Color.White;
            this.uploadToCloudButton.Location = new System.Drawing.Point(17, 45);
            this.uploadToCloudButton.Name = "uploadToCloudButton";
            this.uploadToCloudButton.Size = new System.Drawing.Size(99, 23);
            this.uploadToCloudButton.TabIndex = 3;
            this.uploadToCloudButton.TabStop = false;
            this.uploadToCloudButton.Text = "Upload";
            this.uploadToCloudButton.UseVisualStyleBackColor = false;
            this.uploadToCloudButton.Click += new System.EventHandler(this.UploadToCloudButton_Click);
            // 
            // uploadFileNameTextBox
            // 
            this.uploadFileNameTextBox.Location = new System.Drawing.Point(3, 21);
            this.uploadFileNameTextBox.Margin = new System.Windows.Forms.Padding(1, 1, 1, 1);
            this.uploadFileNameTextBox.Name = "uploadFileNameTextBox";
            this.uploadFileNameTextBox.Size = new System.Drawing.Size(131, 20);
            this.uploadFileNameTextBox.TabIndex = 0;
            // 
            // uploadFileNameLabel
            // 
            this.uploadFileNameLabel.AutoSize = true;
            this.uploadFileNameLabel.Location = new System.Drawing.Point(3, 4);
            this.uploadFileNameLabel.Name = "uploadFileNameLabel";
            this.uploadFileNameLabel.Size = new System.Drawing.Size(57, 13);
            this.uploadFileNameLabel.TabIndex = 4;
            this.uploadFileNameLabel.Text = "File Name:";
            // 
            // downloadFileMenuPanel
            // 
            this.downloadFileMenuPanel.BackColor = System.Drawing.SystemColors.ControlDark;
            this.downloadFileMenuPanel.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.downloadFileMenuPanel.Controls.Add(this.uploadedFileListBox);
            this.downloadFileMenuPanel.Controls.Add(this.downloadFromCloudButton);
            this.downloadFileMenuPanel.Location = new System.Drawing.Point(65, 67);
            this.downloadFileMenuPanel.Name = "downloadFileMenuPanel";
            this.downloadFileMenuPanel.Size = new System.Drawing.Size(139, 151);
            this.downloadFileMenuPanel.TabIndex = 5;
            // 
            // downloadFromCloudButton
            // 
            this.downloadFromCloudButton.BackColor = System.Drawing.Color.White;
            this.downloadFromCloudButton.Location = new System.Drawing.Point(17, 115);
            this.downloadFromCloudButton.Name = "downloadFromCloudButton";
            this.downloadFromCloudButton.Size = new System.Drawing.Size(99, 23);
            this.downloadFromCloudButton.TabIndex = 3;
            this.downloadFromCloudButton.TabStop = false;
            this.downloadFromCloudButton.Text = "Download";
            this.downloadFromCloudButton.UseVisualStyleBackColor = false;
            this.downloadFromCloudButton.Click += new System.EventHandler(this.DownloadFromCloudButton_Click);
            // 
            // uploadedFileListBox
            // 
            this.uploadedFileListBox.FormattingEnabled = true;
            this.uploadedFileListBox.Location = new System.Drawing.Point(3, 6);
            this.uploadedFileListBox.Name = "uploadedFileListBox";
            this.uploadedFileListBox.Size = new System.Drawing.Size(131, 108);
            this.uploadedFileListBox.TabIndex = 5;
            // 
            // ArtistAssistantForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.ClientSize = new System.Drawing.Size(1388, 683);
            this.Controls.Add(this.downloadFileMenuPanel);
            this.Controls.Add(this.fileUploadMenuPanel);
            this.Controls.Add(this.scaleItemMenuPanel);
            this.Controls.Add(this.addItemMenuPanel);
            this.Controls.Add(this.createDrawingMenuPanel);
            this.Controls.Add(this.toolbarPanel);
            this.Controls.Add(this.drawingPictureBox);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Margin = new System.Windows.Forms.Padding(1, 1, 1, 1);
            this.MaximizeBox = false;
            this.Name = "ArtistAssistantForm";
            this.Text = "Artist Assistant";
            this.KeyDown += new System.Windows.Forms.KeyEventHandler(this.ArtistAssistantForm_KeyDown);
            this.toolbarPanel.ResumeLayout(false);
            this.createDrawingMenuPanel.ResumeLayout(false);
            this.addItemMenuPanel.ResumeLayout(false);
            this.addItemMenuPanel.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.addHeightNumericUpDown)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.addWidthNumericUpDown)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.treePictureBox)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.rainPictureBox)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pondPictureBox)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pinePictureBox)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.mountainPictureBox)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cloudPictureBox)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.drawingPictureBox)).EndInit();
            this.scaleItemMenuPanel.ResumeLayout(false);
            this.scaleItemMenuPanel.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.scaleHeightNumericUpDown)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.scaleWidthNumericUpDown)).EndInit();
            this.fileUploadMenuPanel.ResumeLayout(false);
            this.fileUploadMenuPanel.PerformLayout();
            this.downloadFileMenuPanel.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel toolbarPanel;
        private System.Windows.Forms.Button newDrawingButton;
        private System.Windows.Forms.Button uploadButton;
        private System.Windows.Forms.Button downloadButton;
        private System.Windows.Forms.Button selectButton;
        private System.Windows.Forms.Button moveButton;
        private System.Windows.Forms.Button scaleButton;
        private System.Windows.Forms.Button deleteButton;
        private System.Windows.Forms.Button duplicateButton;
        private System.Windows.Forms.Button undoButton;
        private System.Windows.Forms.Button sendToBackButton;
        private System.Windows.Forms.Button bringToFrontButton;
        private System.Windows.Forms.Button newObjectButton;
        private System.Windows.Forms.Panel createDrawingMenuPanel;
        private System.Windows.Forms.ColorDialog backgroundColorDialog;
        private System.Windows.Forms.Button colorButton;
        private System.Windows.Forms.Button backgroundFileButton;
        private System.Windows.Forms.OpenFileDialog openFileDialog;
        private System.Windows.Forms.Button startDrawingButton;
        private System.Windows.Forms.Panel addItemMenuPanel;
        private System.Windows.Forms.NumericUpDown addHeightNumericUpDown;
        private System.Windows.Forms.NumericUpDown addWidthNumericUpDown;
        private System.Windows.Forms.PictureBox treePictureBox;
        private System.Windows.Forms.PictureBox rainPictureBox;
        private System.Windows.Forms.PictureBox pondPictureBox;
        private System.Windows.Forms.PictureBox pinePictureBox;
        private System.Windows.Forms.PictureBox mountainPictureBox;
        private System.Windows.Forms.PictureBox cloudPictureBox;
        private System.Windows.Forms.Label addItemHeightLabel;
        private System.Windows.Forms.Label addItemWidthLabel;
        private System.Windows.Forms.PictureBox drawingPictureBox;
        private System.Windows.Forms.Panel scaleItemMenuPanel;
        private System.Windows.Forms.Button scaleObjectButton;
        private System.Windows.Forms.Label scaleHeightLabel;
        private System.Windows.Forms.Label scaleWidthLabel;
        private System.Windows.Forms.NumericUpDown scaleHeightNumericUpDown;
        private System.Windows.Forms.NumericUpDown scaleWidthNumericUpDown;
        private System.Windows.Forms.ToolTip toolTip;
        private System.Windows.Forms.Panel fileUploadMenuPanel;
        private System.Windows.Forms.Button uploadToCloudButton;
        private System.Windows.Forms.TextBox uploadFileNameTextBox;
        private System.Windows.Forms.Label uploadFileNameLabel;
        private System.Windows.Forms.Panel downloadFileMenuPanel;
        private System.Windows.Forms.ListBox uploadedFileListBox;
        private System.Windows.Forms.Button downloadFromCloudButton;
    }
}

